GearAdd = (vehicle player);
GearAdd addMagazine 'Skin_Sniper1_DZ';
GearAdd addMagazine 'ItemMorphine';
GearAdd addMagazine 'ItemBloodbag';
GearAdd addMagazine 'ItemPainkiller'; 
GearAdd addMagazine 'ItemEpinephrine';
GearAdd addMagazine 'ItemSodaPepsi';
GearAdd addMagazine 'FoodSteakCooked';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addWeapon 'Binocular_Vector';
GearAdd addWeapon 'NVGoggles';
GearAdd addWeapon 'ItemGPS';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addBackpack 'DZ_ALICE_Pack_EP1';
(Unitbackpack GearAdd) addMagazineCargo ['ItemBloodbag', 4];
(Unitbackpack GearAdd) addMagazineCargo ['ItemEpinephrine', 4];
(Unitbackpack GearAdd) addMagazineCargo ['ItemSodaPepsi', 4];
(Unitbackpack GearAdd) addMagazineCargo ['ItemBandage', 4];
(Unitbackpack GearAdd) addMagazineCargo ['FoodSteakCooked', 2];
(Unitbackpack GearAdd) addMagazineCargo ['ItemMorphine', 2];